import copy
import random
from typing import List, Optional
from env.models import Ticket

TICKETS: List[dict] = [
    # ─────────────────────────────────────────────────────────────
    # EASY — Billing FAQ (10 tickets, low/medium priority)
    # ─────────────────────────────────────────────────────────────
    {
        "id": "TKT-001",
        "category": "billing",
        "priority": "medium",
        "subject": "Double charge on invoice #4521",
        "opening_message": "Hi, I was charged twice for my subscription this month. Invoice #4521 shows two identical charges of $49.99. This is unacceptable and I need it fixed immediately.",
        "follow_up_info": "My account email is sarah.jones@email.com and both charges appeared on March 3rd.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 3,
        "customer_persona": "impatient",
        "task": "easy",
    },
    {
        "id": "TKT-002",
        "category": "billing",
        "priority": "low",
        "subject": "Refund status for order ORD-8821",
        "opening_message": "I returned an item two weeks ago and still haven't received my refund. Order number is ORD-8821. Where is my money?",
        "follow_up_info": "The return was picked up on February 18th. My account is mike.davis@gmail.com.",
        "required_info_before_close": ["order_id", "account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 3,
        "customer_persona": "impatient",
        "task": "easy",
    },
    {
        "id": "TKT-003",
        "category": "billing",
        "priority": "low",
        "subject": "Invoice shows wrong tax amount",
        "opening_message": "My invoice for February shows $18.50 in tax but I'm in a tax-exempt state. Can you correct this?",
        "follow_up_info": "I'm in Oregon (tax-exempt). Account email: lisa.chen@company.org. Invoice #INV-2024-0892.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 3,
        "customer_persona": "polite",
        "task": "easy",
    },
    {
        "id": "TKT-004",
        "category": "billing",
        "priority": "medium",
        "subject": "Charged for cancelled subscription",
        "opening_message": "I cancelled my subscription on January 31st but got charged on February 1st. I want a full refund.",
        "follow_up_info": "Cancellation confirmation number: CNCL-44892. Account: james.wilson@email.com.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 3,
        "customer_persona": "impatient",
        "task": "easy",
    },
    {
        "id": "TKT-005",
        "category": "billing",
        "priority": "low",
        "subject": "Cannot find invoice for tax purposes",
        "opening_message": "Hello, I need an invoice for my purchase from December for my business tax filing. I can't find it in my account portal.",
        "follow_up_info": "My account email is accounting@techstartup.io and the purchase was in December 2024.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 3,
        "customer_persona": "polite",
        "task": "easy",
    },
    {
        "id": "TKT-006",
        "category": "billing",
        "priority": "low",
        "subject": "Discount code not applied to bill",
        "opening_message": "I used promo code SAVE20 at checkout but my invoice shows full price of $99. The discount was supposed to take off 20%.",
        "follow_up_info": "Order placed yesterday, account email: priya.sharma@email.com, order #ORD-9934.",
        "required_info_before_close": ["account_email", "order_id"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 3,
        "customer_persona": "polite",
        "task": "easy",
    },
    {
        "id": "TKT-007",
        "category": "billing",
        "priority": "medium",
        "subject": "Unexpected annual renewal charge",
        "opening_message": "I just got charged $299 for annual renewal but I thought I was on a monthly plan! I didn't authorize this.",
        "follow_up_info": "Account: carlos.ramirez@business.com. Charge appeared today on Visa ending 4821.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 3,
        "customer_persona": "impatient",
        "task": "easy",
    },
    {
        "id": "TKT-008",
        "category": "billing",
        "priority": "low",
        "subject": "Request to change billing cycle",
        "opening_message": "I'd like to change my billing date from the 1st to the 15th of each month. Is this possible?",
        "follow_up_info": "Account email: emily.parker@home.net. Currently on Basic plan.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 2,
        "customer_persona": "polite",
        "task": "easy",
    },
    {
        "id": "TKT-009",
        "category": "billing",
        "priority": "medium",
        "subject": "Charged after free trial ended",
        "opening_message": "You charged me $39.99 after my free trial. I was under the impression I could cancel before being billed. This feels like a trap.",
        "follow_up_info": "Trial started Feb 1st, account: tom.nguyen@email.com. I want a full refund.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 3,
        "customer_persona": "impatient",
        "task": "easy",
    },
    {
        "id": "TKT-010",
        "category": "billing",
        "priority": "low",
        "subject": "Wrong currency on invoice",
        "opening_message": "My invoice shows USD but I'm in Canada and should be billed in CAD. This makes my expense reports very confusing.",
        "follow_up_info": "Account: anna.schmidt@ca.company.com. I've been with you since 2022.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 2,
        "customer_persona": "polite",
        "task": "easy",
    },

    # ─────────────────────────────────────────────────────────────
    # MEDIUM — Multi-turn complaint handling (10 tickets)
    # ─────────────────────────────────────────────────────────────
    {
        "id": "TKT-011",
        "category": "technical",
        "priority": "medium",
        "subject": "App crashes on login since last update",
        "opening_message": "Your app has been crashing every time I try to log in since the update yesterday. I've tried reinstalling and nothing works. This is completely broken!",
        "follow_up_info": "Using iPhone 14, iOS 17.3, app version 4.2.1. Account: david.kim@email.com.",
        "required_info_before_close": ["account_email", "device_info"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 5,
        "customer_persona": "impatient",
        "task": "medium",
    },
    {
        "id": "TKT-012",
        "category": "account",
        "priority": "medium",
        "subject": "Cannot access account — locked out",
        "opening_message": "I've been locked out of my account for two days. Password reset emails aren't arriving. I have important files in there that I need for work.",
        "follow_up_info": "Account username: rachel.torres. Backup email: rachel.backup@gmail.com. Last login was from Chicago.",
        "required_info_before_close": ["account_email", "account_username"],
        "expected_resolution_type": "account_access_restored",
        "ideal_max_steps": 5,
        "customer_persona": "confused",
        "task": "medium",
    },
    {
        "id": "TKT-013",
        "category": "technical",
        "priority": "medium",
        "subject": "Data export feature not working",
        "opening_message": "I've been trying to export my data for 3 days and the export button just spins and never downloads anything. I need this data urgently for a project.",
        "follow_up_info": "Account: mark.johnson@company.io. Tried Chrome and Firefox, same issue. Export size should be about 50MB.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 5,
        "customer_persona": "polite",
        "task": "medium",
    },
    {
        "id": "TKT-014",
        "category": "account",
        "priority": "medium",
        "subject": "Two-factor authentication breaking login",
        "opening_message": "After enabling 2FA I can't log in anymore. The codes aren't working. I'm not getting SMS codes to my phone. Please help.",
        "follow_up_info": "Account email: julia.white@email.com. Phone number on file: +1-555-0142. Using Google Authenticator but codes are rejected.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "account_access_restored",
        "ideal_max_steps": 5,
        "customer_persona": "confused",
        "task": "medium",
    },
    {
        "id": "TKT-015",
        "category": "technical",
        "priority": "medium",
        "subject": "Integration with Slack stopped working",
        "opening_message": "Our Slack integration stopped sending notifications three days ago. We rely on this for our team's workflow and it's causing missed alerts.",
        "follow_up_info": "Account: ops@techdept.com. Slack workspace: techdept.slack.com. Integration was working until March 10.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 6,
        "customer_persona": "polite",
        "task": "medium",
    },
    {
        "id": "TKT-016",
        "category": "technical",
        "priority": "medium",
        "subject": "File uploads failing with error code 500",
        "opening_message": "All my file uploads are failing with an internal server error (500). I've been trying to upload presentations for a client demo tomorrow. This is stressing me out.",
        "follow_up_info": "Account: helen.brooks@agency.com. Files are PPT format, around 15MB each. Error started this morning.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 5,
        "customer_persona": "impatient",
        "task": "medium",
    },
    {
        "id": "TKT-017",
        "category": "account",
        "priority": "medium",
        "subject": "Team member unable to join workspace",
        "opening_message": "I invited a new team member a week ago but they still can't access our workspace. The invitation link says 'expired' but it's only been 7 days.",
        "follow_up_info": "Admin account: admin@startupxyz.com. New member email: newdev@startupxyz.com. Invite sent March 4.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "account_access_restored",
        "ideal_max_steps": 4,
        "customer_persona": "polite",
        "task": "medium",
    },
    {
        "id": "TKT-018",
        "category": "technical",
        "priority": "medium",
        "subject": "Dashboard showing wrong analytics data",
        "opening_message": "My analytics dashboard shows 0 visitors for the past week but I can see traffic in my server logs. Something is broken on your end.",
        "follow_up_info": "Account: peter.morgan@myblog.com. Dashboard has been wrong since the maintenance window on March 7. I track revenue from this data.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 5,
        "customer_persona": "impatient",
        "task": "medium",
    },
    {
        "id": "TKT-019",
        "category": "account",
        "priority": "medium",
        "subject": "Email notifications stopped arriving",
        "opening_message": "I stopped getting email notifications about my account activity about a week ago. I rely on these to track orders and messages. Did something change?",
        "follow_up_info": "Account: nina.patel@freelance.com. Email: nina.patel@freelance.com. Checked spam folder, nothing there.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 4,
        "customer_persona": "confused",
        "task": "medium",
    },
    {
        "id": "TKT-020",
        "category": "technical",
        "priority": "medium",
        "subject": "Mobile app not syncing with web version",
        "opening_message": "Changes I make on the mobile app don't show up on the web and vice versa. This sync issue has been going on for 5 days and is causing data inconsistencies.",
        "follow_up_info": "Account: ryan.foster@email.com. App version 4.1.9 on Android 13. Web version up to date.",
        "required_info_before_close": ["account_email", "device_info"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 5,
        "customer_persona": "polite",
        "task": "medium",
    },

    # ─────────────────────────────────────────────────────────────
    # HARD — SLA-critical escalation triage (10 tickets)
    # ─────────────────────────────────────────────────────────────
    {
        "id": "TKT-021",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] Complete service outage — production down",
        "opening_message": "Our entire production system is down. We have 50,000 active users unable to access our service. We are losing $10,000 per minute. Our SLA requires 99.9% uptime. This is a breach. We need senior engineering NOW.",
        "follow_up_info": "Enterprise account: cto@bigcorp.com. Contract #ENT-4421. Outage started 09:14 UTC. Incident commander: Alex Chen, +1-650-555-0199.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-022",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] Database connection failures — all API calls failing",
        "opening_message": "100% of our API calls are returning 503 errors for the past 30 minutes. Our mobile app is completely non-functional. We have a live event with 100K users in 2 hours and our SLA is about to breach. This is a P0 incident.",
        "follow_up_info": "Enterprise account: devops@liveevents.com. Account ID: ENT-7892. Error logs showing DB connection pool exhausted.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-023",
        "category": "account",
        "priority": "critical",
        "subject": "[CRITICAL] Data breach suspected — unauthorized access detected",
        "opening_message": "We've detected unauthorized access to our account from unknown IPs. Our security team is seeing data being exfiltrated RIGHT NOW. We need immediate account lockdown and incident response. This triggers our compliance SLA.",
        "follow_up_info": "Enterprise security contact: security@financialcorp.com. Account: ENT-3310. Unauthorized IPs: 185.220.x.x range. DPA agreement is active.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_security",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-024",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] Payment processing completely down — revenue stopped",
        "opening_message": "Our checkout flow is broken. Zero transactions are completing for the last 45 minutes. We're an e-commerce platform processing $500K/day. Every minute of downtime is $350 in lost revenue. SLA breach imminent.",
        "follow_up_info": "Enterprise: payments@retailgiant.com. Account: ENT-6601. Error: Payment gateway returning 502. We need your on-call engineer bridged in immediately.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-025",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] Healthcare data pipeline failure — patient records at risk",
        "opening_message": "Our healthcare data pipeline has failed and patient medication records are not syncing to our clinical system. We have patients being seen right now. This is a HIPAA-covered critical system with a 4-hour SLA. We are already at hour 3.",
        "follow_up_info": "Healthcare enterprise: it-emergency@hospitalgroup.org. Contract: HIPAA-ENT-0021. BAA is in place. Need P1 escalation immediately.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-026",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] CDN failure causing global service degradation",
        "opening_message": "Our CDN integration with your platform is returning 504 timeouts globally. Users in EU, APAC, and US are all affected. Load times are 30+ seconds. We have a 99.95% uptime SLA and we're at 94% right now. Bridge us with your NOC.",
        "follow_up_info": "Enterprise: noc@globalplatform.com. Account ENT-5521. CDN provider: Cloudflare integration failing since 14:22 UTC.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-027",
        "category": "account",
        "priority": "critical",
        "subject": "[CRITICAL] Ransomware attack — need emergency account controls",
        "opening_message": "We are actively under a ransomware attack. Attacker has our admin credentials. We need immediate emergency lockdown of our entire account, revocation of all API keys, and your security incident response team. This is not a drill.",
        "follow_up_info": "CISO: security-emergency@manufacturing.com. Account ENT-8830. We have cyber insurance claim reference: CYB-2024-4421.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_security",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-028",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] Batch job failure — financial reporting deadline in 2 hours",
        "opening_message": "Our end-of-quarter financial batch job has failed and we cannot generate required SEC filings. The deadline is in 2 hours. This is a regulatory compliance emergency. Our contract stipulates 2-hour RTO for critical failures.",
        "follow_up_info": "CFO office: compliance-it@publiccompany.com. Enterprise contract ENT-2201. Job ID: BATCH-Q4-2024-FINAL. Failure at step 7/12.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-029",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] Authentication service down — 200K users locked out",
        "opening_message": "Your OAuth service is returning 500 errors. 200,000 of our users cannot log in. Our social platform has peak usage right now and we're hemorrhaging user trust. SLA says 99.9% auth availability. We're at 0%. Escalate NOW.",
        "follow_up_info": "Enterprise: platform-oncall@socialapp.com. Account ENT-9102. OAuth client ID: oauth_socialapp_prod. Error: Token endpoint returning 500.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-030",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] ML inference API down — autonomous systems halted",
        "opening_message": "Your ML inference API is returning timeouts. Our autonomous warehouse robots are halted because they cannot get inference results. We have 500 workers idle on the floor. Safety protocols require human oversight when AI systems fail — we need this resolved in under 30 minutes per our SLA.",
        "follow_up_info": "Enterprise: operations@warehouseai.com. Contract ENT-7733. API endpoint: /v2/infer timing out since 11:05 local. Safety officer notified.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    # ─────────────────────────────────────────────────────────────
    # NIGHTMARE — Multi-issue tickets (10 tickets, max_steps: 12)
    # Agent must prioritise, gather multiple info types, and handle
    # compound problems (e.g. locked out AND unauthorised charge).
    # ─────────────────────────────────────────────────────────────
    {
        "id": "TKT-031",
        "category": "account",
        "priority": "high",
        "subject": "Account locked AND unauthorised charge of $299",
        "opening_message": "I can't log into my account AND I just got charged $299 that I didn't authorise. I need both fixed immediately. This is a complete disaster.",
        "follow_up_info": "Account email: marcus.bell@email.com. The charge appeared on my Visa ending 3841 this morning.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "account_access_restored",
        "ideal_max_steps": 6,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-032",
        "category": "technical",
        "priority": "high",
        "subject": "Data loss after update AND subscription downgraded without consent",
        "opening_message": "After your forced update last night, three months of my project data is GONE. On top of that, I've been downgraded from Pro to Free without my permission. I'm losing clients over this.",
        "follow_up_info": "Account: diana.foster@design.co. Project name: ClientPortfolio_2024. Was on Pro plan since January.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 7,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-033",
        "category": "billing",
        "priority": "high",
        "subject": "Triple charged this month AND loyalty discount not applied for 6 months",
        "opening_message": "I've been triple-charged for March AND my loyalty discount of 15% hasn't been applied for six months. I've overpaid by nearly $400. I want a full audit and refund.",
        "follow_up_info": "Account: raj.patel@consulting.com. Been a customer for 3 years. Charges on Mastercard ending 7723.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 6,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-034",
        "category": "account",
        "priority": "high",
        "subject": "Team admin access revoked AND 2FA codes not working for entire team",
        "opening_message": "Our team's admin access was randomly revoked this morning AND none of our 2FA codes are working. We have 12 people locked out. We have a product launch in 4 hours.",
        "follow_up_info": "Admin account: ops@launchpad.io. Team workspace: launchpad-prod. We use Google Authenticator.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "account_access_restored",
        "ideal_max_steps": 6,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-035",
        "category": "technical",
        "priority": "high",
        "subject": "API rate limits wrong AND webhooks delivering duplicate events",
        "opening_message": "We're getting 429 errors at 40% of our documented rate limit AND our webhooks are delivering every event 3-4 times. Both issues started after your maintenance window. Our customers are seeing duplicate orders.",
        "follow_up_info": "Account: platform@ecommerce.dev. API key prefix: pk_live_4xR. Webhook endpoint: api.ecommerce.dev/hooks.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 7,
        "customer_persona": "polite",
        "task": "nightmare",
    },
    {
        "id": "TKT-036",
        "category": "billing",
        "priority": "high",
        "subject": "Invoice in wrong currency AND VAT applied incorrectly for EU business",
        "opening_message": "Our invoices are showing USD instead of EUR AND VAT is being charged despite our valid EU VAT number on file. Our accountant flagged this as a compliance issue affecting 8 months of invoices.",
        "follow_up_info": "Account: finance@eurocorp.de. VAT number: DE298765432. We're registered in Germany. All invoices from August onwards affected.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 6,
        "customer_persona": "polite",
        "task": "nightmare",
    },
    {
        "id": "TKT-037",
        "category": "account",
        "priority": "high",
        "subject": "Account merged with wrong user AND private files now visible to stranger",
        "opening_message": "My account has been merged with someone else's account. I can see their files and they may be able to see mine — including confidential client documents. This is a serious privacy breach AND I've lost access to my own dashboard.",
        "follow_up_info": "My account: sarah.knight@legalfirm.com. The other account I can see belongs to someone named 'T. Harrison'. This happened after I updated my email yesterday.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "account_access_restored",
        "ideal_max_steps": 6,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-038",
        "category": "technical",
        "priority": "high",
        "subject": "Mobile app crashes AND desktop version shows corrupted data",
        "opening_message": "Your mobile app crashes immediately on launch AND the desktop version is showing completely corrupted data — wrong figures, missing records, garbled text. I run a small business and can't access anything. I'm losing work hours.",
        "follow_up_info": "Account: owen.zhang@smallbiz.net. iPhone 15 iOS 17.4, app v5.1.2. Desktop: Windows 11, Chrome 123. Issue since yesterday 6pm.",
        "required_info_before_close": ["account_email", "device_info"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 7,
        "customer_persona": "confused",
        "task": "nightmare",
    },
    {
        "id": "TKT-039",
        "category": "billing",
        "priority": "high",
        "subject": "Charged for cancelled seats AND new seats not provisioned after upgrade",
        "opening_message": "We removed 5 seats last month but are still being charged for them. At the same time we added 10 new seats and they haven't been provisioned — those users can't log in. So we're paying for 15 phantom seats.",
        "follow_up_info": "Account admin: it@growingtechco.com. Removed seats on March 1. Added seats on March 15. Invoice #INV-2024-0344.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 7,
        "customer_persona": "polite",
        "task": "nightmare",
    },
    {
        "id": "TKT-040",
        "category": "technical",
        "priority": "high",
        "subject": "SSO broken AND audit logs deleted — compliance audit tomorrow",
        "opening_message": "Our SSO integration stopped working so 200 employees can't log in. Worse, when I checked the admin panel, the last 30 days of audit logs are GONE. We have a SOC2 compliance audit TOMORROW morning. Both issues need to be resolved tonight.",
        "follow_up_info": "IT Director: compliance@enterprise.com. SSO provider: Okta. Audit log gap: Feb 15 - Mar 15. Contract: ENT-5543.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 5,
        "customer_persona": "impatient",
        "task": "nightmare",
    },

    # ─────────────────────────────────────────────────────────────
    # EASY — Additional billing scenarios (10 tickets, TKT-041–050)
    # ─────────────────────────────────────────────────────────────
    {
        "id": "TKT-041",
        "category": "billing",
        "priority": "low",
        "subject": "Promo price not honored after plan upgrade",
        "opening_message": "I was on a promotional rate of $19/month. When I upgraded to the Pro plan, the promo was removed and now I'm paying full price. My promo was supposed to be locked in for 12 months.",
        "follow_up_info": "Account: felix.hart@email.com. Promo code: EARLYBIRD2024. Upgraded on March 20. I have the original promo email if needed.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 3,
        "customer_persona": "polite",
        "task": "easy",
    },
    {
        "id": "TKT-042",
        "category": "billing",
        "priority": "low",
        "subject": "Duplicate payment via PayPal and credit card",
        "opening_message": "I accidentally paid my invoice twice — once via PayPal and once with my credit card. Both payments went through. Invoice #INV-7741. I need the duplicate refunded.",
        "follow_up_info": "Account: grace.lee@personal.com. PayPal transaction: PP-4821-XYZ, Credit card: Visa ending 5512. Both on March 18.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 3,
        "customer_persona": "polite",
        "task": "easy",
    },
    {
        "id": "TKT-043",
        "category": "billing",
        "priority": "medium",
        "subject": "Charged for users I already removed from account",
        "opening_message": "I removed 3 team members from my account two weeks ago but the invoice still shows charges for all of them. Why am I still being billed for people who don't have access?",
        "follow_up_info": "Admin account: hr@techfirm.io. Removed users on March 5. Current invoice #INV-2024-0412. Total overcharge: $60.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 3,
        "customer_persona": "impatient",
        "task": "easy",
    },
    {
        "id": "TKT-044",
        "category": "billing",
        "priority": "low",
        "subject": "Need itemized invoice for enterprise audit",
        "opening_message": "Our finance department needs a fully itemized invoice showing per-seat pricing, add-on costs, and tax breakdown for our annual payment. The invoice I have is just a single line item.",
        "follow_up_info": "Account: billing@mediumcorp.com. Invoice #INV-ANN-2024-001 for $12,000 paid January 5. Audit deadline is end of month.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 2,
        "customer_persona": "polite",
        "task": "easy",
    },
    {
        "id": "TKT-045",
        "category": "billing",
        "priority": "medium",
        "subject": "Charged full price after referral credit should have applied",
        "opening_message": "My friend referred me and I was supposed to get $30 credit on my first invoice. I just got billed $79.99 with no credit applied. The referral code was used at signup.",
        "follow_up_info": "Account: henry.zhang@email.net. Referral code used: REF-FRIEND-4421. Invoice #INV-2024-FIRST. Signed up March 10.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 3,
        "customer_persona": "polite",
        "task": "easy",
    },
    {
        "id": "TKT-046",
        "category": "billing",
        "priority": "low",
        "subject": "Plan downgrade not reflected in billing",
        "opening_message": "I downgraded from Business to Starter plan on February 28th but my March invoice charged me Business plan pricing of $149 instead of $49. I have the downgrade confirmation email.",
        "follow_up_info": "Account: independent.jo@freelance.me. Downgrade confirmation #DG-88312. Invoice #INV-MAR-2024.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 3,
        "customer_persona": "polite",
        "task": "easy",
    },
    {
        "id": "TKT-047",
        "category": "billing",
        "priority": "medium",
        "subject": "Card declined but was still charged",
        "opening_message": "My card was declined during payment and I got a failed payment notice. But when I checked my bank statement, the charge of $59.99 actually went through. Now I'm showing both 'failed' in your system and charged on my bank.",
        "follow_up_info": "Account: vivian.cross@home.com. Bank shows charge on March 22. Your system shows payment status 'failed'. Card: Amex ending 3309.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 3,
        "customer_persona": "confused",
        "task": "easy",
    },
    {
        "id": "TKT-048",
        "category": "billing",
        "priority": "low",
        "subject": "Request for payment receipt for company reimbursement",
        "opening_message": "Hi, I need a formal payment receipt for my $149 charge last month to submit to my company for reimbursement. The PDF in my account portal doesn't have our company name or address on it.",
        "follow_up_info": "Account: alex.brown@personal.net. Payment date: March 1. Company name for receipt: Acme Corp Inc. Company address: 123 Main St, Austin TX 78701.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 2,
        "customer_persona": "polite",
        "task": "easy",
    },
    {
        "id": "TKT-049",
        "category": "billing",
        "priority": "medium",
        "subject": "Subscription reactivated without my permission after cancellation",
        "opening_message": "I cancelled my subscription 3 months ago and now I see it's been reactivated and I've been charged for the past 2 months without my consent. I never logged back in or clicked anything to reactivate.",
        "follow_up_info": "Account: sophie.turner@email.org. Cancelled December 2023. Unexpected charges in January and February 2024. Total: $79.98.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 3,
        "customer_persona": "impatient",
        "task": "easy",
    },
    {
        "id": "TKT-050",
        "category": "billing",
        "priority": "low",
        "subject": "Wrong VAT rate applied to invoice",
        "opening_message": "You've applied a 20% VAT rate to my invoice but I'm in Ireland where the standard VAT rate is 23%. This creates problems for my VAT return. Can you issue a corrected invoice?",
        "follow_up_info": "Account: patrick.o@dublin.ie. VAT number: IE8765432A. Invoice #INV-EU-2024-0187. Difference: €2.80.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 2,
        "customer_persona": "polite",
        "task": "easy",
    },

    # ─────────────────────────────────────────────────────────────
    # MEDIUM — Additional technical/account scenarios (TKT-051–060)
    # ─────────────────────────────────────────────────────────────
    {
        "id": "TKT-051",
        "category": "account",
        "priority": "medium",
        "subject": "Password reset link expired before I could use it",
        "opening_message": "I requested a password reset and clicked the link within 5 minutes but it says 'link expired'. I've tried 4 times now and the same thing keeps happening. I'm completely locked out.",
        "follow_up_info": "Account username: charlie.brooks. Email: charlie.brooks@mail.com. Using Gmail on iPhone, clicking link directly from email app.",
        "required_info_before_close": ["account_email", "account_username"],
        "expected_resolution_type": "account_access_restored",
        "ideal_max_steps": 4,
        "customer_persona": "confused",
        "task": "medium",
    },
    {
        "id": "TKT-052",
        "category": "technical",
        "priority": "medium",
        "subject": "Search functionality returning no results since update",
        "opening_message": "Since your update on March 12th, the search bar returns zero results for anything — even searching for existing document titles. This was the main way I navigated the platform. My whole workflow is broken.",
        "follow_up_info": "Account: maya.anderson@research.edu. Using Firefox 124 on MacBook Pro M2. Issue started exactly after March 12 update.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 5,
        "customer_persona": "polite",
        "task": "medium",
    },
    {
        "id": "TKT-053",
        "category": "account",
        "priority": "medium",
        "subject": "Account email change stuck in verification loop",
        "opening_message": "I'm trying to update my account email address. I get the verification email, click the link, it says 'email updated', but then my account still shows the old email. I've done this six times.",
        "follow_up_info": "Current email: old.address@work.com. New email: my.personal@gmail.com. Account ID shows ACC-552198.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "account_access_restored",
        "ideal_max_steps": 4,
        "customer_persona": "impatient",
        "task": "medium",
    },
    {
        "id": "TKT-054",
        "category": "technical",
        "priority": "medium",
        "subject": "PDF export feature generates blank pages",
        "opening_message": "Whenever I export a report to PDF, the file downloads but all pages are blank. This affects all reports, not just one. I urgently need these for a board meeting tomorrow and I've never had this problem before.",
        "follow_up_info": "Account: diana.price@boardreports.com. Reports are around 20 pages each. Tried downloading on both Mac and Windows — same blank result. Issue started 2 days ago.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 5,
        "customer_persona": "impatient",
        "task": "medium",
    },
    {
        "id": "TKT-055",
        "category": "account",
        "priority": "medium",
        "subject": "Guest link sharing not working for external collaborators",
        "opening_message": "I shared a guest link with my external contractors but they say it shows 'access denied' when they click it. The link works when I test it while logged in, but they can't access it without an account. How do I share without requiring them to sign up?",
        "follow_up_info": "Account: project.manager@consultancy.biz. Shared project: Q2 Campaign. Link expires April 30. Three external contractors affected.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 4,
        "customer_persona": "polite",
        "task": "medium",
    },
    {
        "id": "TKT-056",
        "category": "technical",
        "priority": "medium",
        "subject": "Calendar integration not syncing with Google Calendar",
        "opening_message": "I connected my Google Calendar three weeks ago and it was working fine. Since last Tuesday the sync stopped — new events I create don't appear in Google Calendar and vice versa. I've tried reconnecting twice.",
        "follow_up_info": "Account: olivia.james@consultant.me. Google account: olivia.james@gmail.com. Reconnected on March 14 and March 17. Both times sync initially appeared to work then stopped.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 5,
        "customer_persona": "polite",
        "task": "medium",
    },
    {
        "id": "TKT-057",
        "category": "account",
        "priority": "medium",
        "subject": "Multi-language setting keeps reverting to English",
        "opening_message": "I set my account language to Spanish in settings but every time I log out and back in, it reverts to English. I've changed it at least 10 times. The setting won't stick. I use this professionally in Spanish.",
        "follow_up_info": "Account: lucia.gomez@espanol.es. Language selected: Español (España). Browser: Chrome 122. Tried on mobile app too — same issue.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 4,
        "customer_persona": "impatient",
        "task": "medium",
    },
    {
        "id": "TKT-058",
        "category": "technical",
        "priority": "medium",
        "subject": "Automated report emails not being sent",
        "opening_message": "I set up weekly automated report emails for my team but nobody is receiving them. The schedule shows they're set up correctly and the last send date is blank even though the first one should have gone out 3 weeks ago.",
        "follow_up_info": "Account: team.lead@operations.co. Report schedule: Every Monday 8AM EST. Recipients: 8 email addresses. Set up March 4. No reports ever received.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 5,
        "customer_persona": "polite",
        "task": "medium",
    },
    {
        "id": "TKT-059",
        "category": "account",
        "priority": "medium",
        "subject": "Profile photo keeps disappearing after upload",
        "opening_message": "Every time I upload a profile photo it shows up for a few minutes and then disappears. I've tried JPG, PNG, different sizes. The photo is there when I look at my profile but my teammates say they see no photo. It's been a week.",
        "follow_up_info": "Account: nate.fisher@design.studio. Tried files from 50KB to 2MB. All standard formats. Teammates using Chrome, Safari, and the mobile app all see no photo.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 4,
        "customer_persona": "confused",
        "task": "medium",
    },
    {
        "id": "TKT-060",
        "category": "technical",
        "priority": "medium",
        "subject": "Bulk import CSV failing with no error message",
        "opening_message": "I'm trying to import 5,000 contacts via CSV. The import process runs for about 2 minutes, shows a progress bar, then silently fails — no success message, no error, and no contacts appear in the system. I've tried smaller files too.",
        "follow_up_info": "Account: crm.admin@salesdept.com. CSV has columns: name, email, phone, company. Tried with 100 rows, 500 rows, 5000 rows — all fail the same way. File encoding: UTF-8.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 5,
        "customer_persona": "impatient",
        "task": "medium",
    },

    # ─────────────────────────────────────────────────────────────
    # HARD — Additional SLA-critical scenarios (TKT-061–070)
    # ─────────────────────────────────────────────────────────────
    {
        "id": "TKT-061",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] Search index corrupted — e-commerce site unsearchable",
        "opening_message": "Our entire product search index is corrupted. Customers searching for products get zero results or completely wrong matches. We're an e-commerce site with 2 million products and 50K daily active users. Revenue impact is already $80K in the last hour. SLA breach in 30 minutes.",
        "follow_up_info": "Enterprise: engineering@shoppingplatform.com. Account ENT-3312. Search engine: Elasticsearch integration. Corruption detected at 10:15 UTC. Index ID: prod-search-v3.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-062",
        "category": "account",
        "priority": "critical",
        "subject": "[CRITICAL] Insider threat detected — admin account compromised",
        "opening_message": "Our security team has identified that an admin account is being used by an unauthorized person inside our network. The account has already deleted 14 user accounts and modified billing settings. We need emergency suspension of all admin accounts and full audit trail immediately.",
        "follow_up_info": "Security lead: infosec@lawfirm.com. Account ENT-4420. Compromised admin: admin@lawfirm.com. Activity log shows unauthorized actions from 09:00-09:45 UTC today.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_security",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-063",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] Email delivery system down — transactional emails not sending",
        "opening_message": "Your email delivery integration has been down for 90 minutes. Our users are not receiving order confirmations, password resets, or OTP codes. We have a fintech app — users cannot authenticate or transact. This breaches our 99.9% SLA. We need P0 response.",
        "follow_up_info": "Enterprise: devops@fintechapp.io. Account ENT-6671. Email provider integration: SendGrid via your platform. Bounce rate: 100% since 08:30 UTC. 12,000 users affected.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-064",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] GDPR data deletion request — 72-hour deadline in 4 hours",
        "opening_message": "We received a formal GDPR Article 17 right-to-erasure request that was logged in your system 68 hours ago. The legally required 72-hour deletion window expires in 4 hours. The data has NOT been deleted. We are facing regulatory fines of up to €20 million if this is not completed NOW.",
        "follow_up_info": "DPO contact: privacy@eurocorporate.de. Account ENT-2209. Data subject request ID: GDPR-2024-0441. Submitted: March 18 09:00 CET. Deadline: March 21 09:00 CET.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-065",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] Real-time trading feed latency spike — financial losses occurring",
        "opening_message": "Our real-time market data feed through your platform has latency spikes of 800ms (normal: <10ms). We're a proprietary trading firm and every millisecond matters. We've had 23 failed trades in the last 20 minutes causing direct financial losses. SLA guarantees <50ms. Escalate immediately.",
        "follow_up_info": "Trading desk: tech@quanttrading.com. Enterprise contract: SLA-FIN-889. Feed subscription: market-data-pro-realtime. Latency logs attached to this ticket.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-066",
        "category": "account",
        "priority": "critical",
        "subject": "[CRITICAL] Entire organization's data inaccessible — S3 permissions broken",
        "opening_message": "As of 30 minutes ago, NONE of our organization's data is accessible. Every file, database, and resource returns 'Access Denied'. 800 employees cannot work. We believe a permissions change during your scheduled maintenance has broken our entire account. This is a complete business stoppage.",
        "follow_up_info": "CTO: engineering@globalconsulting.com. Organization ID: ORG-ENT-1144. Started: 06:00 UTC during maintenance window. Our DR plan requires 2-hour RTO — we're at 30 minutes.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-067",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] 911 dispatch software integration failure — public safety risk",
        "opening_message": "Our 911 call-routing integration with your platform has failed. Dispatch cannot see caller locations or incident histories in real-time. We are routing emergency calls blind. This is a public safety emergency. Our contract mandates 15-minute RTO for P0 incidents. We are at minute 12.",
        "follow_up_info": "Emergency IT: it-emergency@countysheriff.gov. Contract: GOV-ENT-0091. Integration: CAD-system-v2 webhook. Failure since 22:47 local. Backup manual dispatch activated but capacity is 30%.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-068",
        "category": "billing",
        "priority": "critical",
        "subject": "[CRITICAL] Enterprise contract renewal failed — service suspension in 2 hours",
        "opening_message": "Our auto-renewal failed due to a billing system error on YOUR side. We have proof the payment cleared our bank. If service is suspended in 2 hours, 1,200 employees lose access and our $4M/year production pipeline stops. We have a PO and bank confirmation ready. Do NOT suspend our service.",
        "follow_up_info": "CFO office: legal@enterprise-client.com. Account ENT-7743. Annual contract value: $4.2M. Bank wire confirmation: WIRE-20240321-4M. Renewal date: today. Payment sent March 19.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-069",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] CI/CD pipeline broken — 40 engineers blocked from deploying",
        "opening_message": "Your platform's GitHub integration is completely broken. Our CI/CD pipeline has been blocked for 3 hours. 40 engineers cannot deploy code. We have a critical security patch that must be deployed today per regulatory requirements. SLA mandates 2-hour resolution for P0s.",
        "follow_up_info": "VP Engineering: vpe@softwareco.com. Account ENT-8812. GitHub org: softwareco-prod. Integration error: webhook signature validation failing. Security patch: CVE-2024-1234 fix due today.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-070",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] IoT device management platform down — 50K field devices offline",
        "opening_message": "Your IoT device management API is returning timeouts. 50,000 of our field sensors across 12 cities have gone offline — including water quality monitors, traffic sensors, and air quality detectors. This is smart city infrastructure. Regulatory bodies are already calling us. SLA breach happened 10 minutes ago.",
        "follow_up_info": "Smart city tech lead: operations@smartcity.gov. Contract: GOV-IOT-2241. Device fleet: IOT-FLEET-PROD-001. API endpoint: /v3/devices/command timing out. Started: 15:30 local.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },

    # ─────────────────────────────────────────────────────────────
    # NIGHTMARE — Additional multi-issue compound scenarios (TKT-071–080)
    # ─────────────────────────────────────────────────────────────
    {
        "id": "TKT-071",
        "category": "technical",
        "priority": "high",
        "subject": "Entire project deleted AND team members lost their roles",
        "opening_message": "Someone on our team accidentally deleted our main project and now ALL team members show as 'guest' with no roles assigned. We've lost 6 weeks of work and none of us can even access the admin panel to fix the permissions. We have a client presentation in 3 hours.",
        "follow_up_info": "Admin: project.lead@creative.agency. Workspace: creative-agency-main. Deleted project: Q2-Campaign-Final. 8 team members affected. Client presentation at 2PM EST.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 7,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-072",
        "category": "billing",
        "priority": "high",
        "subject": "Fraudulent charge AND account used to send spam — now blacklisted",
        "opening_message": "There's a fraudulent charge of $450 on my account AND I've received reports that my account has been used to send spam emails to thousands of people. I've been blacklisted by email providers. I didn't do this — my account was hacked. I need the charge reversed AND my sender reputation fixed.",
        "follow_up_info": "Account: legitimate.user@business.com. Fraudulent charge: March 20, $450.00. Spam reports from: Spamhaus, Barracuda. I have not sent any emails since March 15.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "account_access_restored",
        "ideal_max_steps": 7,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-073",
        "category": "account",
        "priority": "high",
        "subject": "GDPR data request ignored AND account auto-closed after 30 days",
        "opening_message": "I submitted a GDPR data access request 35 days ago and never received my data. THEN my account was auto-closed because of 'inactivity' even though I was actively waiting for support. Now I'm locked out, can't see my data, and my subscription was refunded partially without my consent. THREE issues to fix.",
        "follow_up_info": "Former account: citizen.rights@eu-country.de. GDPR request ticket: SUP-GDPR-20240215. Account closure notification received March 21. Partial refund: €23 of €87 paid.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "account_access_restored",
        "ideal_max_steps": 8,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-074",
        "category": "technical",
        "priority": "high",
        "subject": "API keys rotated without notice AND old keys still billed",
        "opening_message": "You rotated our API keys without any notice, breaking all our production integrations. We found out because our system went down — not from any communication from you. To make it worse, we're still being charged for the old (now invalid) API tier AND our new keys are limited to a lower rate. We've lost 4 hours of production time.",
        "follow_up_info": "CTO: tech@startup.io. Account ENT-4421. Old key prefix: sk_prod_abc123. New key prefix: sk_prod_xyz789. Billing shows Premium tier but new key has Standard limits. Downtime: 04:00-08:00 UTC.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 7,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-075",
        "category": "billing",
        "priority": "high",
        "subject": "Annual plan auto-renewed at wrong price AND downgraded simultaneously",
        "opening_message": "My annual plan auto-renewed at $1,200 (up from $800 last year — 50% increase with no notice) AND at the same time I was 'downgraded' to a lower feature tier. So I'm paying MORE for LESS. I never agreed to a price increase, there was no notice, and I want either the original price or a full refund so I can cancel.",
        "follow_up_info": "Account: long.time.customer@business.net. Customer since 2021. Previous annual invoice: $800. New invoice: #INV-ANN-2024 for $1,200. Renewal date: March 1. Features removed: advanced analytics, API access.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 6,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-076",
        "category": "technical",
        "priority": "high",
        "subject": "Cloud backup corrupted AND restore job overwrote good data",
        "opening_message": "Our cloud backup was corrupted. When we tried to restore from the previous backup, your system ran an automated job that OVERWROTE our current good data with the corrupted backup. We now have no valid copy of our database anywhere in your system. 18 months of data is at risk.",
        "follow_up_info": "Account: dba@criticaldata.com. Database: prod-postgresql-main. Last known good state: March 19 23:00 UTC. Corrupted backup: March 20. Auto-restore job ran: March 21 02:00 UTC. We have our own partial export from March 18.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 6,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-077",
        "category": "account",
        "priority": "high",
        "subject": "Wrong account merged after support session AND original data overwritten",
        "opening_message": "A support agent helped me earlier today and accidentally merged my account with another customer's account instead of unlinking a duplicate. My original account data has been partially overwritten with a stranger's information. I can see their personal data, they can likely see mine, AND my own project history is now mixed with theirs. This is a privacy breach AND data integrity issue.",
        "follow_up_info": "My account: verified.user@mycompany.com. Support session: SUP-SESSION-20240321-1430. Incorrect merge with: unknown customer (I can see their name is 'Jordan Lee'). Ticket I raised today: TKT-PREV-8821.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "account_access_restored",
        "ideal_max_steps": 7,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-078",
        "category": "technical",
        "priority": "high",
        "subject": "Permissions cascade error locked out all sub-admins AND broke SSO",
        "opening_message": "After a permissions change made by one of our admins (following your support team's guidance), a cascade error has propagated and locked out all 12 of our sub-administrators. Additionally, the SSO integration broke and now none of our 300 users can log in via corporate SSO. We're effectively fully locked out of our enterprise account.",
        "follow_up_info": "IT Director: it.director@enterprise.org. Account ENT-6612. Change made following advice in ticket SUP-ENT-20240320. SSO provider: Azure AD. 12 sub-admins + 300 SSO users affected.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 6,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-079",
        "category": "billing",
        "priority": "high",
        "subject": "Chargeback filed by mistake AND account suspended — payroll deadline today",
        "opening_message": "Our finance team accidentally filed a chargeback for our last invoice (thinking it was a fraudulent charge — it wasn't). Now our account is suspended due to the chargeback AND we have payroll processing through your platform due in 6 hours. 150 employees won't get paid if this isn't fixed. We want to reverse the chargeback and pay the invoice immediately.",
        "follow_up_info": "CFO: payroll@mediumcorp.com. Account: ENT-3341. Invoice disputed: #INV-MAR-2024 for $2,450. Chargeback ref: CB-2024-7712. Payroll batch: PAYROLL-Q1-MARCH due 5PM EST today.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 6,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-080",
        "category": "technical",
        "priority": "high",
        "subject": "Live webinar platform crashed mid-event AND recordings lost",
        "opening_message": "Your platform crashed in the middle of our paid live webinar with 2,400 attendees. The session ended abruptly with no warning. The recording was not saved — it just disappeared. We have 2,400 angry ticket-purchasers and legal obligations to deliver the content. We also lost the real-time Q&A data that attendees submitted. We need: recordings recovered, compensation plan, and explanation.",
        "follow_up_info": "Event organizer: events@conferencegroup.com. Webinar ID: WEB-2024-ANNUAL-MAIN. Started: 14:00 EST. Crashed: 15:42 EST. Attendees: 2,400 paid at $49 each. Q&A log lost: approximately 890 questions submitted.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 7,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
]

# ── Hierarchy Tickets (Indian Enterprise Context) ─────────────────────────────

HIERARCHY_TICKETS: list[dict] = [
    # hierarchy_easy → maps to easy pool
    {
        "id": "HTKT-001",
        "category": "billing",
        "priority": "low",
        "subject": "UPI autopay not reflecting — monthly subscription",
        "opening_message": "I set up UPI autopay for my ₹499/month plan but it shows unpaid for March. My bank shows the amount was debited. Please check and confirm.",
        "follow_up_info": "UPI ID: user@okaxis. Transaction ref: AXI20260315789012. Amount: ₹499. Bank: Axis Bank.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 4,
        "customer_persona": "polite",
        "task": "easy",
    },
    {
        "id": "HTKT-002",
        "category": "billing",
        "priority": "low",
        "subject": "GST invoice missing from last 3 months",
        "opening_message": "Hi, I need GST invoices for January, February, and March 2026 for my business account. The download button on the billing page gives an error. Can you email them to me?",
        "follow_up_info": "Business account: BIZ-8834. GST No: 29ABCDE1234F1Z5. Email: accounts@startupindia.co",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 3,
        "customer_persona": "polite",
        "task": "easy",
    },
    # hierarchy_medium → maps to medium pool
    {
        "id": "HTKT-003",
        "category": "technical",
        "priority": "medium",
        "subject": "Payment gateway timeout during Big Billion Days checkout",
        "opening_message": "During the Big Billion Days sale, my payment keeps timing out at checkout. I've tried 3 different cards and UPI. The cart clears after each failure and I have to re-add items. This has happened 5 times now. I'm losing deals because items go out of stock.",
        "follow_up_info": "Order attempts: ORD-BBD-7712, ORD-BBD-7718, ORD-BBD-7723. Browser: Chrome 120 on Android 14. App version: 8.2.1.",
        "required_info_before_close": ["account_email", "device_info"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 5,
        "customer_persona": "impatient",
        "task": "medium",
    },
    {
        "id": "HTKT-004",
        "category": "account",
        "priority": "medium",
        "subject": "KYC document rejected 3 times — account restricted",
        "opening_message": "I've submitted my Aadhaar card for KYC verification THREE times and it keeps getting rejected with no explanation. Now my account is restricted and I can't make purchases. The error just says 'document not accepted'. What's the actual problem?",
        "follow_up_info": "Account: ACC-KYC-9981. Aadhaar last 4: 7823. Submissions: March 1, March 8, March 15. All showed status 'rejected' within 24 hours.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "account_access_restored",
        "ideal_max_steps": 5,
        "customer_persona": "confused",
        "task": "medium",
    },
    # hierarchy_hard → maps to hard pool
    {
        "id": "HTKT-005",
        "category": "billing",
        "priority": "critical",
        "subject": "₹2.5L unauthorized transaction — SLA breach imminent",
        "opening_message": "URGENT: There's an unauthorized transaction of ₹2,50,000 on our corporate account from 30 minutes ago. We're a listed company and our SLA requires fraud resolution within 2 hours. The payment went to an unknown UPI ID. I need this frozen and reversed IMMEDIATELY. Our compliance team is already involved.",
        "follow_up_info": "Corporate account: CORP-ENT-2201. Transaction: TXN-20260315-250K. UPI destination: unknown@ybl. CFO email: cfo@enterprise.in. SLA contract: SLA-ENT-445.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_security",
        "ideal_max_steps": 3,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "HTKT-006",
        "category": "technical",
        "priority": "critical",
        "subject": "Production API returning 500s — 10K RPM affected",
        "opening_message": "Our production integration is completely down. Your API started returning 500 errors 15 minutes ago. We're processing 10,000 requests per minute and every single one is failing. Our customers are seeing payment failures. This is a P0 incident. We need your engineering team NOW.",
        "follow_up_info": "API key: pk_live_****4892. Endpoint: /v1/transactions. Error: 500 Internal Server Error. Started: 14:30 IST. Impact: ~150K failed transactions so far.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 3,
        "customer_persona": "impatient",
        "task": "hard",
    },
]

# Merge hierarchy tickets into main list for ID lookups
TICKETS.extend(HIERARCHY_TICKETS)


class TicketStore:
    def __init__(self) -> None:
        self._by_task: dict[str, list[dict]] = {
            "easy": [], "medium": [], "hard": [], "nightmare": [],
        }
        for ticket in TICKETS:
            task = ticket["task"]
            if task in self._by_task:
                self._by_task[task].append(ticket)

    def get_random_by_task(self, task: str) -> dict:
        pool = self._by_task.get(task)
        if not pool:
            raise ValueError(
                f"Unknown task '{task}'. Must be one of: {list(self._by_task.keys())}"
            )
        # Deep copy so mutations never bleed across sessions
        return copy.deepcopy(random.choice(pool))

    def get_by_id(self, ticket_id: str) -> Optional[dict]:
        for ticket in TICKETS:
            if ticket["id"] == ticket_id:
                return dict(ticket)
        return None

    def all_tasks(self) -> list[str]:
        return list(self._by_task.keys())


# Singleton
ticket_store = TicketStore()
