import copy
import random
from typing import List, Optional
from env.models import Ticket

TICKETS: List[dict] = [
    # ─────────────────────────────────────────────────────────────
    # EASY — Billing FAQ (10 tickets, low/medium priority)
    # ─────────────────────────────────────────────────────────────
    {
        "id": "TKT-001",
        "category": "billing",
        "priority": "medium",
        "subject": "Double charge on invoice #4521",
        "opening_message": "Hi, I was charged twice for my subscription this month. Invoice #4521 shows two identical charges of $49.99. This is unacceptable and I need it fixed immediately.",
        "follow_up_info": "My account email is sarah.jones@email.com and both charges appeared on March 3rd.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 3,
        "customer_persona": "impatient",
        "task": "easy",
    },
    {
        "id": "TKT-002",
        "category": "billing",
        "priority": "low",
        "subject": "Refund status for order ORD-8821",
        "opening_message": "I returned an item two weeks ago and still haven't received my refund. Order number is ORD-8821. Where is my money?",
        "follow_up_info": "The return was picked up on February 18th. My account is mike.davis@gmail.com.",
        "required_info_before_close": ["order_id", "account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 3,
        "customer_persona": "impatient",
        "task": "easy",
    },
    {
        "id": "TKT-003",
        "category": "billing",
        "priority": "low",
        "subject": "Invoice shows wrong tax amount",
        "opening_message": "My invoice for February shows $18.50 in tax but I'm in a tax-exempt state. Can you correct this?",
        "follow_up_info": "I'm in Oregon (tax-exempt). Account email: lisa.chen@company.org. Invoice #INV-2024-0892.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 3,
        "customer_persona": "polite",
        "task": "easy",
    },
    {
        "id": "TKT-004",
        "category": "billing",
        "priority": "medium",
        "subject": "Charged for cancelled subscription",
        "opening_message": "I cancelled my subscription on January 31st but got charged on February 1st. I want a full refund.",
        "follow_up_info": "Cancellation confirmation number: CNCL-44892. Account: james.wilson@email.com.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 3,
        "customer_persona": "impatient",
        "task": "easy",
    },
    {
        "id": "TKT-005",
        "category": "billing",
        "priority": "low",
        "subject": "Cannot find invoice for tax purposes",
        "opening_message": "Hello, I need an invoice for my purchase from December for my business tax filing. I can't find it in my account portal.",
        "follow_up_info": "My account email is accounting@techstartup.io and the purchase was in December 2024.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 3,
        "customer_persona": "polite",
        "task": "easy",
    },
    {
        "id": "TKT-006",
        "category": "billing",
        "priority": "low",
        "subject": "Discount code not applied to bill",
        "opening_message": "I used promo code SAVE20 at checkout but my invoice shows full price of $99. The discount was supposed to take off 20%.",
        "follow_up_info": "Order placed yesterday, account email: priya.sharma@email.com, order #ORD-9934.",
        "required_info_before_close": ["account_email", "order_id"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 3,
        "customer_persona": "polite",
        "task": "easy",
    },
    {
        "id": "TKT-007",
        "category": "billing",
        "priority": "medium",
        "subject": "Unexpected annual renewal charge",
        "opening_message": "I just got charged $299 for annual renewal but I thought I was on a monthly plan! I didn't authorize this.",
        "follow_up_info": "Account: carlos.ramirez@business.com. Charge appeared today on Visa ending 4821.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 3,
        "customer_persona": "impatient",
        "task": "easy",
    },
    {
        "id": "TKT-008",
        "category": "billing",
        "priority": "low",
        "subject": "Request to change billing cycle",
        "opening_message": "I'd like to change my billing date from the 1st to the 15th of each month. Is this possible?",
        "follow_up_info": "Account email: emily.parker@home.net. Currently on Basic plan.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 2,
        "customer_persona": "polite",
        "task": "easy",
    },
    {
        "id": "TKT-009",
        "category": "billing",
        "priority": "medium",
        "subject": "Charged after free trial ended",
        "opening_message": "You charged me $39.99 after my free trial. I was under the impression I could cancel before being billed. This feels like a trap.",
        "follow_up_info": "Trial started Feb 1st, account: tom.nguyen@email.com. I want a full refund.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 3,
        "customer_persona": "impatient",
        "task": "easy",
    },
    {
        "id": "TKT-010",
        "category": "billing",
        "priority": "low",
        "subject": "Wrong currency on invoice",
        "opening_message": "My invoice shows USD but I'm in Canada and should be billed in CAD. This makes my expense reports very confusing.",
        "follow_up_info": "Account: anna.schmidt@ca.company.com. I've been with you since 2022.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 2,
        "customer_persona": "polite",
        "task": "easy",
    },

    # ─────────────────────────────────────────────────────────────
    # MEDIUM — Multi-turn complaint handling (10 tickets)
    # ─────────────────────────────────────────────────────────────
    {
        "id": "TKT-011",
        "category": "technical",
        "priority": "medium",
        "subject": "App crashes on login since last update",
        "opening_message": "Your app has been crashing every time I try to log in since the update yesterday. I've tried reinstalling and nothing works. This is completely broken!",
        "follow_up_info": "Using iPhone 14, iOS 17.3, app version 4.2.1. Account: david.kim@email.com.",
        "required_info_before_close": ["account_email", "device_info"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 5,
        "customer_persona": "impatient",
        "task": "medium",
    },
    {
        "id": "TKT-012",
        "category": "account",
        "priority": "medium",
        "subject": "Cannot access account — locked out",
        "opening_message": "I've been locked out of my account for two days. Password reset emails aren't arriving. I have important files in there that I need for work.",
        "follow_up_info": "Account username: rachel.torres. Backup email: rachel.backup@gmail.com. Last login was from Chicago.",
        "required_info_before_close": ["account_email", "account_username"],
        "expected_resolution_type": "account_access_restored",
        "ideal_max_steps": 5,
        "customer_persona": "confused",
        "task": "medium",
    },
    {
        "id": "TKT-013",
        "category": "technical",
        "priority": "medium",
        "subject": "Data export feature not working",
        "opening_message": "I've been trying to export my data for 3 days and the export button just spins and never downloads anything. I need this data urgently for a project.",
        "follow_up_info": "Account: mark.johnson@company.io. Tried Chrome and Firefox, same issue. Export size should be about 50MB.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 5,
        "customer_persona": "polite",
        "task": "medium",
    },
    {
        "id": "TKT-014",
        "category": "account",
        "priority": "medium",
        "subject": "Two-factor authentication breaking login",
        "opening_message": "After enabling 2FA I can't log in anymore. The codes aren't working. I'm not getting SMS codes to my phone. Please help.",
        "follow_up_info": "Account email: julia.white@email.com. Phone number on file: +1-555-0142. Using Google Authenticator but codes are rejected.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "account_access_restored",
        "ideal_max_steps": 5,
        "customer_persona": "confused",
        "task": "medium",
    },
    {
        "id": "TKT-015",
        "category": "technical",
        "priority": "medium",
        "subject": "Integration with Slack stopped working",
        "opening_message": "Our Slack integration stopped sending notifications three days ago. We rely on this for our team's workflow and it's causing missed alerts.",
        "follow_up_info": "Account: ops@techdept.com. Slack workspace: techdept.slack.com. Integration was working until March 10.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 6,
        "customer_persona": "polite",
        "task": "medium",
    },
    {
        "id": "TKT-016",
        "category": "technical",
        "priority": "medium",
        "subject": "File uploads failing with error code 500",
        "opening_message": "All my file uploads are failing with an internal server error (500). I've been trying to upload presentations for a client demo tomorrow. This is stressing me out.",
        "follow_up_info": "Account: helen.brooks@agency.com. Files are PPT format, around 15MB each. Error started this morning.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 5,
        "customer_persona": "impatient",
        "task": "medium",
    },
    {
        "id": "TKT-017",
        "category": "account",
        "priority": "medium",
        "subject": "Team member unable to join workspace",
        "opening_message": "I invited a new team member a week ago but they still can't access our workspace. The invitation link says 'expired' but it's only been 7 days.",
        "follow_up_info": "Admin account: admin@startupxyz.com. New member email: newdev@startupxyz.com. Invite sent March 4.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "account_access_restored",
        "ideal_max_steps": 4,
        "customer_persona": "polite",
        "task": "medium",
    },
    {
        "id": "TKT-018",
        "category": "technical",
        "priority": "medium",
        "subject": "Dashboard showing wrong analytics data",
        "opening_message": "My analytics dashboard shows 0 visitors for the past week but I can see traffic in my server logs. Something is broken on your end.",
        "follow_up_info": "Account: peter.morgan@myblog.com. Dashboard has been wrong since the maintenance window on March 7. I track revenue from this data.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 5,
        "customer_persona": "impatient",
        "task": "medium",
    },
    {
        "id": "TKT-019",
        "category": "account",
        "priority": "medium",
        "subject": "Email notifications stopped arriving",
        "opening_message": "I stopped getting email notifications about my account activity about a week ago. I rely on these to track orders and messages. Did something change?",
        "follow_up_info": "Account: nina.patel@freelance.com. Email: nina.patel@freelance.com. Checked spam folder, nothing there.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 4,
        "customer_persona": "confused",
        "task": "medium",
    },
    {
        "id": "TKT-020",
        "category": "technical",
        "priority": "medium",
        "subject": "Mobile app not syncing with web version",
        "opening_message": "Changes I make on the mobile app don't show up on the web and vice versa. This sync issue has been going on for 5 days and is causing data inconsistencies.",
        "follow_up_info": "Account: ryan.foster@email.com. App version 4.1.9 on Android 13. Web version up to date.",
        "required_info_before_close": ["account_email", "device_info"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 5,
        "customer_persona": "polite",
        "task": "medium",
    },

    # ─────────────────────────────────────────────────────────────
    # HARD — SLA-critical escalation triage (10 tickets)
    # ─────────────────────────────────────────────────────────────
    {
        "id": "TKT-021",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] Complete service outage — production down",
        "opening_message": "Our entire production system is down. We have 50,000 active users unable to access our service. We are losing $10,000 per minute. Our SLA requires 99.9% uptime. This is a breach. We need senior engineering NOW.",
        "follow_up_info": "Enterprise account: cto@bigcorp.com. Contract #ENT-4421. Outage started 09:14 UTC. Incident commander: Alex Chen, +1-650-555-0199.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-022",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] Database connection failures — all API calls failing",
        "opening_message": "100% of our API calls are returning 503 errors for the past 30 minutes. Our mobile app is completely non-functional. We have a live event with 100K users in 2 hours and our SLA is about to breach. This is a P0 incident.",
        "follow_up_info": "Enterprise account: devops@liveevents.com. Account ID: ENT-7892. Error logs showing DB connection pool exhausted.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-023",
        "category": "account",
        "priority": "critical",
        "subject": "[CRITICAL] Data breach suspected — unauthorized access detected",
        "opening_message": "We've detected unauthorized access to our account from unknown IPs. Our security team is seeing data being exfiltrated RIGHT NOW. We need immediate account lockdown and incident response. This triggers our compliance SLA.",
        "follow_up_info": "Enterprise security contact: security@financialcorp.com. Account: ENT-3310. Unauthorized IPs: 185.220.x.x range. DPA agreement is active.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_security",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-024",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] Payment processing completely down — revenue stopped",
        "opening_message": "Our checkout flow is broken. Zero transactions are completing for the last 45 minutes. We're an e-commerce platform processing $500K/day. Every minute of downtime is $350 in lost revenue. SLA breach imminent.",
        "follow_up_info": "Enterprise: payments@retailgiant.com. Account: ENT-6601. Error: Payment gateway returning 502. We need your on-call engineer bridged in immediately.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-025",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] Healthcare data pipeline failure — patient records at risk",
        "opening_message": "Our healthcare data pipeline has failed and patient medication records are not syncing to our clinical system. We have patients being seen right now. This is a HIPAA-covered critical system with a 4-hour SLA. We are already at hour 3.",
        "follow_up_info": "Healthcare enterprise: it-emergency@hospitalgroup.org. Contract: HIPAA-ENT-0021. BAA is in place. Need P1 escalation immediately.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-026",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] CDN failure causing global service degradation",
        "opening_message": "Our CDN integration with your platform is returning 504 timeouts globally. Users in EU, APAC, and US are all affected. Load times are 30+ seconds. We have a 99.95% uptime SLA and we're at 94% right now. Bridge us with your NOC.",
        "follow_up_info": "Enterprise: noc@globalplatform.com. Account ENT-5521. CDN provider: Cloudflare integration failing since 14:22 UTC.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-027",
        "category": "account",
        "priority": "critical",
        "subject": "[CRITICAL] Ransomware attack — need emergency account controls",
        "opening_message": "We are actively under a ransomware attack. Attacker has our admin credentials. We need immediate emergency lockdown of our entire account, revocation of all API keys, and your security incident response team. This is not a drill.",
        "follow_up_info": "CISO: security-emergency@manufacturing.com. Account ENT-8830. We have cyber insurance claim reference: CYB-2024-4421.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_security",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-028",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] Batch job failure — financial reporting deadline in 2 hours",
        "opening_message": "Our end-of-quarter financial batch job has failed and we cannot generate required SEC filings. The deadline is in 2 hours. This is a regulatory compliance emergency. Our contract stipulates 2-hour RTO for critical failures.",
        "follow_up_info": "CFO office: compliance-it@publiccompany.com. Enterprise contract ENT-2201. Job ID: BATCH-Q4-2024-FINAL. Failure at step 7/12.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-029",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] Authentication service down — 200K users locked out",
        "opening_message": "Your OAuth service is returning 500 errors. 200,000 of our users cannot log in. Our social platform has peak usage right now and we're hemorrhaging user trust. SLA says 99.9% auth availability. We're at 0%. Escalate NOW.",
        "follow_up_info": "Enterprise: platform-oncall@socialapp.com. Account ENT-9102. OAuth client ID: oauth_socialapp_prod. Error: Token endpoint returning 500.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    {
        "id": "TKT-030",
        "category": "technical",
        "priority": "critical",
        "subject": "[CRITICAL] ML inference API down — autonomous systems halted",
        "opening_message": "Your ML inference API is returning timeouts. Our autonomous warehouse robots are halted because they cannot get inference results. We have 500 workers idle on the floor. Safety protocols require human oversight when AI systems fail — we need this resolved in under 30 minutes per our SLA.",
        "follow_up_info": "Enterprise: operations@warehouseai.com. Contract ENT-7733. API endpoint: /v2/infer timing out since 11:05 local. Safety officer notified.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 2,
        "customer_persona": "impatient",
        "task": "hard",
    },
    # ─────────────────────────────────────────────────────────────
    # NIGHTMARE — Multi-issue tickets (10 tickets, max_steps: 12)
    # Agent must prioritise, gather multiple info types, and handle
    # compound problems (e.g. locked out AND unauthorised charge).
    # ─────────────────────────────────────────────────────────────
    {
        "id": "TKT-031",
        "category": "account",
        "priority": "high",
        "subject": "Account locked AND unauthorised charge of $299",
        "opening_message": "I can't log into my account AND I just got charged $299 that I didn't authorise. I need both fixed immediately. This is a complete disaster.",
        "follow_up_info": "Account email: marcus.bell@email.com. The charge appeared on my Visa ending 3841 this morning.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "account_access_restored",
        "ideal_max_steps": 6,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-032",
        "category": "technical",
        "priority": "high",
        "subject": "Data loss after update AND subscription downgraded without consent",
        "opening_message": "After your forced update last night, three months of my project data is GONE. On top of that, I've been downgraded from Pro to Free without my permission. I'm losing clients over this.",
        "follow_up_info": "Account: diana.foster@design.co. Project name: ClientPortfolio_2024. Was on Pro plan since January.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 7,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-033",
        "category": "billing",
        "priority": "high",
        "subject": "Triple charged this month AND loyalty discount not applied for 6 months",
        "opening_message": "I've been triple-charged for March AND my loyalty discount of 15% hasn't been applied for six months. I've overpaid by nearly $400. I want a full audit and refund.",
        "follow_up_info": "Account: raj.patel@consulting.com. Been a customer for 3 years. Charges on Mastercard ending 7723.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 6,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-034",
        "category": "account",
        "priority": "high",
        "subject": "Team admin access revoked AND 2FA codes not working for entire team",
        "opening_message": "Our team's admin access was randomly revoked this morning AND none of our 2FA codes are working. We have 12 people locked out. We have a product launch in 4 hours.",
        "follow_up_info": "Admin account: ops@launchpad.io. Team workspace: launchpad-prod. We use Google Authenticator.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "account_access_restored",
        "ideal_max_steps": 6,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-035",
        "category": "technical",
        "priority": "high",
        "subject": "API rate limits wrong AND webhooks delivering duplicate events",
        "opening_message": "We're getting 429 errors at 40% of our documented rate limit AND our webhooks are delivering every event 3-4 times. Both issues started after your maintenance window. Our customers are seeing duplicate orders.",
        "follow_up_info": "Account: platform@ecommerce.dev. API key prefix: pk_live_4xR. Webhook endpoint: api.ecommerce.dev/hooks.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 7,
        "customer_persona": "polite",
        "task": "nightmare",
    },
    {
        "id": "TKT-036",
        "category": "billing",
        "priority": "high",
        "subject": "Invoice in wrong currency AND VAT applied incorrectly for EU business",
        "opening_message": "Our invoices are showing USD instead of EUR AND VAT is being charged despite our valid EU VAT number on file. Our accountant flagged this as a compliance issue affecting 8 months of invoices.",
        "follow_up_info": "Account: finance@eurocorp.de. VAT number: DE298765432. We're registered in Germany. All invoices from August onwards affected.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "billing_clarification",
        "ideal_max_steps": 6,
        "customer_persona": "polite",
        "task": "nightmare",
    },
    {
        "id": "TKT-037",
        "category": "account",
        "priority": "high",
        "subject": "Account merged with wrong user AND private files now visible to stranger",
        "opening_message": "My account has been merged with someone else's account. I can see their files and they may be able to see mine — including confidential client documents. This is a serious privacy breach AND I've lost access to my own dashboard.",
        "follow_up_info": "My account: sarah.knight@legalfirm.com. The other account I can see belongs to someone named 'T. Harrison'. This happened after I updated my email yesterday.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "account_access_restored",
        "ideal_max_steps": 6,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
    {
        "id": "TKT-038",
        "category": "technical",
        "priority": "high",
        "subject": "Mobile app crashes AND desktop version shows corrupted data",
        "opening_message": "Your mobile app crashes immediately on launch AND the desktop version is showing completely corrupted data — wrong figures, missing records, garbled text. I run a small business and can't access anything. I'm losing work hours.",
        "follow_up_info": "Account: owen.zhang@smallbiz.net. iPhone 15 iOS 17.4, app v5.1.2. Desktop: Windows 11, Chrome 123. Issue since yesterday 6pm.",
        "required_info_before_close": ["account_email", "device_info"],
        "expected_resolution_type": "technical_fix_provided",
        "ideal_max_steps": 7,
        "customer_persona": "confused",
        "task": "nightmare",
    },
    {
        "id": "TKT-039",
        "category": "billing",
        "priority": "high",
        "subject": "Charged for cancelled seats AND new seats not provisioned after upgrade",
        "opening_message": "We removed 5 seats last month but are still being charged for them. At the same time we added 10 new seats and they haven't been provisioned — those users can't log in. So we're paying for 15 phantom seats.",
        "follow_up_info": "Account admin: it@growingtechco.com. Removed seats on March 1. Added seats on March 15. Invoice #INV-2024-0344.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "refund_initiated",
        "ideal_max_steps": 7,
        "customer_persona": "polite",
        "task": "nightmare",
    },
    {
        "id": "TKT-040",
        "category": "technical",
        "priority": "high",
        "subject": "SSO broken AND audit logs deleted — compliance audit tomorrow",
        "opening_message": "Our SSO integration stopped working so 200 employees can't log in. Worse, when I checked the admin panel, the last 30 days of audit logs are GONE. We have a SOC2 compliance audit TOMORROW morning. Both issues need to be resolved tonight.",
        "follow_up_info": "IT Director: compliance@enterprise.com. SSO provider: Okta. Audit log gap: Feb 15 - Mar 15. Contract: ENT-5543.",
        "required_info_before_close": ["account_email"],
        "expected_resolution_type": "escalated_to_engineering",
        "ideal_max_steps": 5,
        "customer_persona": "impatient",
        "task": "nightmare",
    },
]


class TicketStore:
    def __init__(self) -> None:
        self._by_task: dict[str, list[dict]] = {"easy": [], "medium": [], "hard": [], "nightmare": []}
        for ticket in TICKETS:
            self._by_task[ticket["task"]].append(ticket)

    def get_random_by_task(self, task: str) -> dict:
        pool = self._by_task.get(task)
        if not pool:
            raise ValueError(f"Unknown task '{task}'. Must be one of: easy, medium, hard")
        # Deep copy so mutations (e.g. to required_info_before_close list) never
        # bleed across sessions that share the same underlying ticket dict.
        return copy.deepcopy(random.choice(pool))

    def get_by_id(self, ticket_id: str) -> Optional[dict]:
        for ticket in TICKETS:
            if ticket["id"] == ticket_id:
                return dict(ticket)
        return None

    def all_tasks(self) -> list[str]:
        return list(self._by_task.keys())


# Singleton
ticket_store = TicketStore()
