"""
env/user_db.py — In-memory user and order database for grounded agent responses.

Covers three domains: food_delivery, e_commerce, ticket_booking.
~15 users, ~30 orders. Half the existing tickets are linked via customer_email /
related_order_ids; the other half remain data-less so nothing breaks.
"""

from __future__ import annotations
from typing import Dict, Any, Literal, Union

# ── Users ──────────────────────────────────────────────────────────────────────

USERS: Dict[str, Dict[str, Any]] = {
    # Food Delivery
    "sarah.jones@email.com": {
        "domain": "food_delivery",
        "name": "Sarah Jones",
        "phone": "+91-9876543210",
        "account_status": "active",
        "loyalty_tier": "gold",
        "joined": "2023-03-15",
    },
    "rahul.verma@gmail.com": {
        "domain": "food_delivery",
        "name": "Rahul Verma",
        "phone": "+91-9812345678",
        "account_status": "active",
        "loyalty_tier": "silver",
        "joined": "2022-11-01",
    },
    "priya.sharma@yahoo.com": {
        "domain": "food_delivery",
        "name": "Priya Sharma",
        "phone": "+91-9900001111",
        "account_status": "active",
        "loyalty_tier": "bronze",
        "joined": "2024-01-20",
    },
    "amit.gupta@hotmail.com": {
        "domain": "food_delivery",
        "name": "Amit Gupta",
        "phone": "+91-9823456789",
        "account_status": "suspended",
        "loyalty_tier": "gold",
        "joined": "2021-06-10",
    },
    # E-Commerce
    "meera.nair@email.com": {
        "domain": "e_commerce",
        "name": "Meera Nair",
        "phone": "+91-9845678901",
        "account_status": "active",
        "loyalty_tier": "platinum",
        "joined": "2020-09-05",
    },
    "vikram.singh@outlook.com": {
        "domain": "e_commerce",
        "name": "Vikram Singh",
        "phone": "+91-9867890123",
        "account_status": "active",
        "loyalty_tier": "gold",
        "joined": "2022-04-18",
    },
    "kavita.patel@gmail.com": {
        "domain": "e_commerce",
        "name": "Kavita Patel",
        "phone": "+91-9834567890",
        "account_status": "active",
        "loyalty_tier": "silver",
        "joined": "2023-07-22",
    },
    "rohit.mehta@email.com": {
        "domain": "e_commerce",
        "name": "Rohit Mehta",
        "phone": "+91-9856789012",
        "account_status": "active",
        "loyalty_tier": "bronze",
        "joined": "2024-02-14",
    },
    "anita.desai@gmail.com": {
        "domain": "e_commerce",
        "name": "Anita Desai",
        "phone": "+91-9878901234",
        "account_status": "active",
        "loyalty_tier": "gold",
        "joined": "2021-12-01",
    },
    # Ticket Booking
    "suresh.kumar@email.com": {
        "domain": "ticket_booking",
        "name": "Suresh Kumar",
        "phone": "+91-9890123456",
        "account_status": "active",
        "loyalty_tier": "silver",
        "joined": "2022-08-30",
    },
    "deepa.iyer@gmail.com": {
        "domain": "ticket_booking",
        "name": "Deepa Iyer",
        "phone": "+91-9812098765",
        "account_status": "active",
        "loyalty_tier": "gold",
        "joined": "2021-03-12",
    },
    "arun.pillai@yahoo.com": {
        "domain": "ticket_booking",
        "name": "Arun Pillai",
        "phone": "+91-9823187654",
        "account_status": "active",
        "loyalty_tier": "bronze",
        "joined": "2023-10-05",
    },
    "sunita.reddy@hotmail.com": {
        "domain": "ticket_booking",
        "name": "Sunita Reddy",
        "phone": "+91-9834276543",
        "account_status": "active",
        "loyalty_tier": "silver",
        "joined": "2022-05-17",
    },
    "manoj.rao@email.com": {
        "domain": "ticket_booking",
        "name": "Manoj Rao",
        "phone": "+91-9845365432",
        "account_status": "suspended",
        "loyalty_tier": "bronze",
        "joined": "2023-01-09",
    },
    "neha.joshi@gmail.com": {
        "domain": "food_delivery",
        "name": "Neha Joshi",
        "phone": "+91-9856454321",
        "account_status": "active",
        "loyalty_tier": "silver",
        "joined": "2023-06-28",
    },
    # ── New users for expanded scenarios ──────────────────────────────────────
    "arjun.krishna@gmail.com": {
        "domain": "food_delivery",
        "name": "Arjun Krishna",
        "phone": "+91-9901234567",
        "account_status": "active",
        "loyalty_tier": "silver",
        "joined": "2023-08-11",
    },
    "sanjay.patel@gmail.com": {
        "domain": "food_delivery",
        "name": "Sanjay Patel",
        "phone": "+91-9912345678",
        "account_status": "active",
        "loyalty_tier": "platinum",
        "joined": "2020-04-05",
    },
    "pooja.bhat@gmail.com": {
        "domain": "food_delivery",
        "name": "Pooja Bhat",
        "phone": "+91-9923456789",
        "account_status": "active",
        "loyalty_tier": "bronze",
        "joined": "2024-03-18",
    },
    "fatima.sheikh@email.com": {
        "domain": "e_commerce",
        "name": "Fatima Sheikh",
        "phone": "+91-9934567890",
        "account_status": "active",
        "loyalty_tier": "platinum",
        "joined": "2019-11-22",
    },
    "kiran.reddy@email.com": {
        "domain": "e_commerce",
        "name": "Kiran Reddy",
        "phone": "+91-9945678901",
        "account_status": "suspended",
        "loyalty_tier": "silver",
        "joined": "2022-07-30",
        "suspension_reason": "payment_dispute",
    },
    "geeta.nambiar@email.com": {
        "domain": "e_commerce",
        "name": "Geeta Nambiar",
        "phone": "+91-9956789012",
        "account_status": "active",
        "loyalty_tier": "bronze",
        "joined": "2024-01-05",
    },
    "ravi.tiwari@yahoo.com": {
        "domain": "ticket_booking",
        "name": "Ravi Tiwari",
        "phone": "+91-9967890123",
        "account_status": "active",
        "loyalty_tier": "gold",
        "joined": "2021-09-14",
    },
    "tanvi.mehta@hotmail.com": {
        "domain": "ticket_booking",
        "name": "Tanvi Mehta",
        "phone": "+91-9978901234",
        "account_status": "active",
        "loyalty_tier": "silver",
        "joined": "2022-12-03",
    },
}

# ── Orders ─────────────────────────────────────────────────────────────────────

ORDERS: Dict[str, Dict[str, Any]] = {
    # Food Delivery Orders
    "ORD-FD-8821": {
        "domain": "food_delivery",
        "user_email": "sarah.jones@email.com",
        "status": "delivered",
        "placed_at": "2026-04-22T18:30:00",
        "delivered_at": "2026-04-22T19:15:00",
        "restaurant": "Biryani House",
        "items": ["Chicken Biryani", "Raita", "Gulab Jamun"],
        "amount": 499,
        "payment_method": "UPI",
        "delivery_address": "12 MG Road, Bangalore",
    },
    "ORD-FD-9102": {
        "domain": "food_delivery",
        "user_email": "sarah.jones@email.com",
        "status": "refunded",
        "placed_at": "2026-04-18T12:00:00",
        "restaurant": "Pizza Palace",
        "items": ["Margherita Pizza", "Coke"],
        "amount": 349,
        "payment_method": "Credit Card",
        "delivery_address": "12 MG Road, Bangalore",
        "refund_amount": 349,
        "refund_status": "processed",
    },
    "ORD-FD-7743": {
        "domain": "food_delivery",
        "user_email": "rahul.verma@gmail.com",
        "status": "cancelled",
        "placed_at": "2026-04-21T20:10:00",
        "restaurant": "Dosa Corner",
        "items": ["Masala Dosa", "Filter Coffee"],
        "amount": 199,
        "payment_method": "UPI",
        "delivery_address": "45 Anna Nagar, Chennai",
        "cancellation_reason": "restaurant_closed",
    },
    "ORD-FD-6654": {
        "domain": "food_delivery",
        "user_email": "rahul.verma@gmail.com",
        "status": "delivered",
        "placed_at": "2026-04-20T19:45:00",
        "delivered_at": "2026-04-20T20:30:00",
        "restaurant": "Burger King",
        "items": ["Whopper", "Fries", "Pepsi"],
        "amount": 279,
        "payment_method": "Debit Card",
        "delivery_address": "45 Anna Nagar, Chennai",
    },
    "ORD-FD-5512": {
        "domain": "food_delivery",
        "user_email": "priya.sharma@yahoo.com",
        "status": "out_for_delivery",
        "placed_at": "2026-04-24T13:00:00",
        "restaurant": "Haldiram's",
        "items": ["Pav Bhaji", "Lassi"],
        "amount": 259,
        "payment_method": "UPI",
        "delivery_address": "7 Lajpat Nagar, Delhi",
    },
    "ORD-FD-4433": {
        "domain": "food_delivery",
        "user_email": "amit.gupta@hotmail.com",
        "status": "delivered",
        "placed_at": "2026-04-19T21:00:00",
        "delivered_at": "2026-04-19T21:45:00",
        "restaurant": "McDonald's",
        "items": ["McSpicy", "McFlurry"],
        "amount": 319,
        "payment_method": "Credit Card",
        "delivery_address": "3 FC Road, Pune",
    },
    "ORD-FD-3301": {
        "domain": "food_delivery",
        "user_email": "neha.joshi@gmail.com",
        "status": "delivered",
        "placed_at": "2026-04-23T14:30:00",
        "delivered_at": "2026-04-23T15:10:00",
        "restaurant": "Subway",
        "items": ["Veggie Delite Sub", "Cookie"],
        "amount": 229,
        "payment_method": "UPI",
        "delivery_address": "22 Bandra West, Mumbai",
    },
    # E-Commerce Orders
    "ORD-EC-2201": {
        "domain": "e_commerce",
        "user_email": "meera.nair@email.com",
        "status": "delivered",
        "placed_at": "2026-04-15T10:00:00",
        "delivered_at": "2026-04-18T14:00:00",
        "items": [{"name": "iPhone 15 Case", "qty": 1, "price": 799}],
        "amount": 799,
        "payment_method": "Credit Card",
        "shipping_address": "18 Koramangala, Bangalore",
    },
    "ORD-EC-3345": {
        "domain": "e_commerce",
        "user_email": "meera.nair@email.com",
        "status": "return_initiated",
        "placed_at": "2026-04-10T11:30:00",
        "delivered_at": "2026-04-13T09:00:00",
        "items": [{"name": "Wireless Headphones", "qty": 1, "price": 2499}],
        "amount": 2499,
        "payment_method": "UPI",
        "shipping_address": "18 Koramangala, Bangalore",
        "return_reason": "defective_product",
        "return_initiated_at": "2026-04-21T10:00:00",
    },
    "ORD-EC-4456": {
        "domain": "e_commerce",
        "user_email": "vikram.singh@outlook.com",
        "status": "shipped",
        "placed_at": "2026-04-22T09:00:00",
        "estimated_delivery": "2026-04-26T18:00:00",
        "items": [
            {"name": "Laptop Stand", "qty": 1, "price": 1299},
            {"name": "USB Hub", "qty": 1, "price": 599},
        ],
        "amount": 1898,
        "payment_method": "Debit Card",
        "shipping_address": "56 Sector 18, Noida",
        "tracking_number": "DTDC-78903421",
    },
    "ORD-EC-5567": {
        "domain": "e_commerce",
        "user_email": "kavita.patel@gmail.com",
        "status": "delivered",
        "placed_at": "2026-04-16T15:00:00",
        "delivered_at": "2026-04-19T11:00:00",
        "items": [{"name": "Yoga Mat", "qty": 1, "price": 699}],
        "amount": 699,
        "payment_method": "UPI",
        "shipping_address": "9 Navrangpura, Ahmedabad",
    },
    "ORD-EC-6678": {
        "domain": "e_commerce",
        "user_email": "rohit.mehta@email.com",
        "status": "processing",
        "placed_at": "2026-04-24T08:30:00",
        "items": [{"name": "Gaming Mouse", "qty": 1, "price": 1599}],
        "amount": 1599,
        "payment_method": "Credit Card",
        "shipping_address": "31 Powai, Mumbai",
    },
    "ORD-EC-7789": {
        "domain": "e_commerce",
        "user_email": "anita.desai@gmail.com",
        "status": "refunded",
        "placed_at": "2026-04-08T14:00:00",
        "delivered_at": "2026-04-11T10:00:00",
        "items": [{"name": "Silk Saree", "qty": 1, "price": 3499}],
        "amount": 3499,
        "payment_method": "Net Banking",
        "shipping_address": "14 Aundh, Pune",
        "refund_amount": 3499,
        "refund_status": "processed",
        "refund_processed_at": "2026-04-20T12:00:00",
    },
    "ORD-EC-8890": {
        "domain": "e_commerce",
        "user_email": "anita.desai@gmail.com",
        "status": "delivered",
        "placed_at": "2026-04-01T10:00:00",
        "delivered_at": "2026-04-04T16:00:00",
        "items": [{"name": "Kitchen Mixer", "qty": 1, "price": 2199}],
        "amount": 2199,
        "payment_method": "Credit Card",
        "shipping_address": "14 Aundh, Pune",
    },
    # Ticket Booking Orders
    "ORD-TB-1122": {
        "domain": "ticket_booking",
        "user_email": "suresh.kumar@email.com",
        "status": "confirmed",
        "booked_at": "2026-04-20T09:00:00",
        "event": "IPL Match - RCB vs MI",
        "venue": "M. Chinnaswamy Stadium, Bangalore",
        "event_date": "2026-05-02T19:30:00",
        "seats": ["Stand B - Row 12 - Seat 45", "Stand B - Row 12 - Seat 46"],
        "amount": 1800,
        "payment_method": "UPI",
    },
    "ORD-TB-2233": {
        "domain": "ticket_booking",
        "user_email": "deepa.iyer@gmail.com",
        "status": "cancelled",
        "booked_at": "2026-04-10T11:00:00",
        "event": "AR Rahman Concert",
        "venue": "Palace Grounds, Bangalore",
        "event_date": "2026-04-28T18:00:00",
        "seats": ["VIP Section - Row 2 - Seat 15"],
        "amount": 3500,
        "payment_method": "Credit Card",
        "cancellation_reason": "event_cancelled",
        "refund_status": "pending",
    },
    "ORD-TB-3344": {
        "domain": "ticket_booking",
        "user_email": "deepa.iyer@gmail.com",
        "status": "confirmed",
        "booked_at": "2026-04-22T14:00:00",
        "event": "Standup Comedy Night",
        "venue": "Canvas Laugh Club, Mumbai",
        "event_date": "2026-05-10T20:00:00",
        "seats": ["Row 5 - Seat 8", "Row 5 - Seat 9"],
        "amount": 1200,
        "payment_method": "UPI",
    },
    "ORD-TB-4455": {
        "domain": "ticket_booking",
        "user_email": "arun.pillai@yahoo.com",
        "status": "confirmed",
        "booked_at": "2026-04-21T16:30:00",
        "event": "Kochi-Tuskers vs Chennai Super Kings (Kerala Blasters)",
        "venue": "Jawaharlal Nehru Stadium, Kochi",
        "event_date": "2026-05-05T15:00:00",
        "seats": ["East Stand - Row 8 - Seat 22"],
        "amount": 850,
        "payment_method": "Debit Card",
    },
    "ORD-TB-5566": {
        "domain": "ticket_booking",
        "user_email": "sunita.reddy@hotmail.com",
        "status": "delivered",
        "booked_at": "2026-04-05T10:00:00",
        "event": "Tollywood Awards Night",
        "venue": "Hyderabad International Convention Centre",
        "event_date": "2026-04-20T19:00:00",
        "seats": ["Hall A - Row 10 - Seat 33"],
        "amount": 2200,
        "payment_method": "Credit Card",
    },
    "ORD-TB-6677": {
        "domain": "ticket_booking",
        "user_email": "suresh.kumar@email.com",
        "status": "confirmed",
        "booked_at": "2026-04-23T12:00:00",
        "event": "Tech Summit 2026",
        "venue": "HICC, Hyderabad",
        "event_date": "2026-05-15T09:00:00",
        "seats": ["Conference Hall B - Seat 112"],
        "amount": 999,
        "payment_method": "UPI",
    },
    "ORD-TB-7788": {
        "domain": "ticket_booking",
        "user_email": "manoj.rao@email.com",
        "status": "payment_failed",
        "booked_at": "2026-04-23T18:00:00",
        "event": "Film Festival Screening",
        "venue": "PVR Cinemas, Chennai",
        "event_date": "2026-04-27T15:00:00",
        "seats": ["Row 4 - Seat 18"],
        "amount": 350,
        "payment_method": "UPI",
        "failure_reason": "upi_timeout",
    },
    # Additional cross-domain orders for edge cases
    "ORD-FD-2200": {
        "domain": "food_delivery",
        "user_email": "sarah.jones@email.com",
        "status": "delivered",
        "placed_at": "2026-04-10T20:00:00",
        "delivered_at": "2026-04-10T20:50:00",
        "restaurant": "Chinese Garden",
        "items": ["Fried Rice", "Manchurian", "Spring Rolls"],
        "amount": 389,
        "payment_method": "Credit Card",
        "delivery_address": "12 MG Road, Bangalore",
    },
    "ORD-EC-9901": {
        "domain": "e_commerce",
        "user_email": "vikram.singh@outlook.com",
        "status": "delivered",
        "placed_at": "2026-04-05T10:30:00",
        "delivered_at": "2026-04-08T12:00:00",
        "items": [{"name": "Bluetooth Speaker", "qty": 1, "price": 1899}],
        "amount": 1899,
        "payment_method": "UPI",
        "shipping_address": "56 Sector 18, Noida",
    },
    "ORD-TB-8899": {
        "domain": "ticket_booking",
        "user_email": "deepa.iyer@gmail.com",
        "status": "refund_processed",
        "booked_at": "2026-03-15T11:00:00",
        "event": "Classical Music Evening",
        "venue": "NCPA, Mumbai",
        "event_date": "2026-04-01T19:00:00",
        "seats": ["Row 3 - Seat 7"],
        "amount": 1500,
        "payment_method": "Credit Card",
        "refund_amount": 1500,
        "refund_status": "processed",
        "refund_processed_at": "2026-04-05T10:00:00",
    },
    # ── New orders for expanded scenarios ─────────────────────────────────────
    # Food delivery
    "ORD-FD-1100": {
        "domain": "food_delivery",
        "user_email": "arjun.krishna@gmail.com",
        "status": "delivered",
        "placed_at": "2026-04-23T19:30:00",
        "delivered_at": "2026-04-23T20:25:00",
        "restaurant": "Spice Garden",
        "items": ["Butter Chicken", "Garlic Naan", "Lassi"],
        "amount": 389,
        "payment_method": "UPI",
        "delivery_address": "88 Indiranagar, Bangalore",
        "delivery_issue": "food_spilled_damaged",
    },
    "ORD-FD-1101": {
        "domain": "food_delivery",
        "user_email": "sanjay.patel@gmail.com",
        "status": "delivered",
        "placed_at": "2026-04-24T12:15:00",
        "delivered_at": "2026-04-24T13:05:00",
        "restaurant": "Patel's Kitchen",
        "items": ["Dal Makhani", "Jeera Rice", "Gulab Jamun", "Paneer Tikka"],
        "amount": 549,
        "payment_method": "Credit Card",
        "delivery_address": "12 CG Road, Ahmedabad",
        "delivery_issue": "missing_items",
        "missing_items": ["Gulab Jamun", "Paneer Tikka"],
    },
    "ORD-FD-1102": {
        "domain": "food_delivery",
        "user_email": "pooja.bhat@gmail.com",
        "status": "returned_to_facility",
        "placed_at": "2026-04-24T14:00:00",
        "restaurant": "Mangalore Mess",
        "items": ["Fish Curry", "Rice", "Papad"],
        "amount": 299,
        "payment_method": "UPI",
        "delivery_address": "5 Manipal Centre, Mangalore",
        "return_reason": "customer_unavailable",
    },
    "ORD-FD-1103": {
        "domain": "food_delivery",
        "user_email": "sarah.jones@email.com",
        "status": "delivered",
        "placed_at": "2026-04-23T13:00:00",
        "delivered_at": "2026-04-23T13:55:00",
        "restaurant": "Biryani House",
        "items": ["Chicken Biryani", "Raita"],
        "amount": 329,
        "payment_method": "UPI",
        "delivery_address": "12 MG Road, Bangalore",
        "delivery_issue": "wrong_restaurant_food",
        "note": "Items delivered from a different restaurant, packaging was from Burger King",
    },
    "ORD-FD-1104": {
        "domain": "food_delivery",
        "user_email": "rahul.verma@gmail.com",
        "status": "delivered",
        "placed_at": "2026-04-22T21:00:00",
        "delivered_at": "2026-04-22T22:30:00",
        "restaurant": "Dosa Palace",
        "items": ["Masala Dosa", "Sambar", "Coconut Chutney"],
        "amount": 179,
        "payment_method": "UPI",
        "delivery_address": "45 Anna Nagar, Chennai",
        "delivery_issue": "food_cold",
        "delivery_time_minutes": 90,
    },
    # E-commerce
    "ORD-EC-1200": {
        "domain": "e_commerce",
        "user_email": "fatima.sheikh@email.com",
        "status": "delivered",
        "placed_at": "2026-04-20T10:00:00",
        "delivered_at": "2026-04-23T14:00:00",
        "items": [{"name": "Banarasi Silk Saree", "qty": 1, "price": 4999}],
        "amount": 4999,
        "payment_method": "Credit Card",
        "shipping_address": "7 Marine Lines, Mumbai",
        "billing_issue": "duplicate_payment",
        "duplicate_charge_amount": 4999,
        "duplicate_charge_date": "2026-04-20T10:02:00",
    },
    "ORD-EC-1201": {
        "domain": "e_commerce",
        "user_email": "fatima.sheikh@email.com",
        "status": "delivery_attempted",
        "placed_at": "2026-04-18T09:30:00",
        "items": [{"name": "Air Purifier", "qty": 1, "price": 7999}],
        "amount": 7999,
        "payment_method": "Net Banking",
        "shipping_address": "7 Marine Lines, Mumbai",
        "delivery_issue": "delivered_wrong_address",
        "wrong_address": "7 Marine Drive, Mumbai",
    },
    "ORD-EC-1202": {
        "domain": "e_commerce",
        "user_email": "geeta.nambiar@email.com",
        "status": "delivered",
        "placed_at": "2026-04-15T11:00:00",
        "delivered_at": "2026-04-18T16:00:00",
        "items": [{"name": "Fitness Tracker", "qty": 1, "price": 2999}],
        "amount": 2999,
        "payment_method": "UPI",
        "shipping_address": "3 Viman Nagar, Pune",
        "loyalty_points_due": 300,
        "loyalty_points_credited": 0,
        "loyalty_issue": "points_not_credited",
    },
    "ORD-EC-1203": {
        "domain": "e_commerce",
        "user_email": "kiran.reddy@email.com",
        "status": "on_hold",
        "placed_at": "2026-04-24T09:00:00",
        "items": [{"name": "Smartwatch", "qty": 1, "price": 5499}],
        "amount": 5499,
        "payment_method": "Credit Card",
        "shipping_address": "21 Banjara Hills, Hyderabad",
        "hold_reason": "account_suspended",
    },
    "ORD-EC-1204": {
        "domain": "e_commerce",
        "user_email": "vikram.singh@outlook.com",
        "status": "delivered",
        "placed_at": "2026-04-12T14:00:00",
        "delivered_at": "2026-04-15T11:00:00",
        "items": [{"name": "Mechanical Keyboard", "qty": 1, "price": 3499}],
        "amount": 3499,
        "payment_method": "Debit Card",
        "shipping_address": "56 Sector 18, Noida",
        "billing_issue": "promo_not_applied",
        "promo_code": "SAVE500",
        "expected_discount": 500,
        "actual_discount": 0,
    },
    "ORD-EC-1205": {
        "domain": "e_commerce",
        "user_email": "anita.desai@gmail.com",
        "status": "delivered",
        "placed_at": "2026-04-17T10:00:00",
        "delivered_at": "2026-04-20T14:00:00",
        "items": [{"name": "Kurta Set (Size M)", "qty": 1, "price": 1299}],
        "amount": 1299,
        "payment_method": "UPI",
        "shipping_address": "14 Aundh, Pune",
        "exchange_request": "size_issue",
        "requested_size": "L",
    },
    # Ticket booking
    "ORD-TB-1300": {
        "domain": "ticket_booking",
        "user_email": "ravi.tiwari@yahoo.com",
        "status": "rescheduled",
        "booked_at": "2026-04-10T10:00:00",
        "event": "Arijit Singh Live Concert",
        "venue": "Jawaharlal Nehru Stadium, Delhi",
        "event_date": "2026-04-30T19:00:00",
        "new_event_date": "2026-06-15T19:00:00",
        "seats": ["Block C - Row 5 - Seat 12", "Block C - Row 5 - Seat 13"],
        "amount": 4500,
        "payment_method": "Credit Card",
        "reschedule_reason": "artist_unavailable",
    },
    "ORD-TB-1301": {
        "domain": "ticket_booking",
        "user_email": "tanvi.mehta@hotmail.com",
        "status": "confirmed",
        "booked_at": "2026-04-23T18:30:00",
        "event": "Punjabi Night — DJ Sukh",
        "venue": "F Bar & Lounge, Bangalore",
        "event_date": "2026-04-27T21:00:00",
        "seats": ["General - Table 8"],
        "amount": 1800,
        "payment_method": "UPI",
        "booking_issue": "wrong_event",
        "intended_event": "Bollywood Night — DJ Ravi",
    },
    "ORD-TB-1302": {
        "domain": "ticket_booking",
        "user_email": "ravi.tiwari@yahoo.com",
        "status": "under_review",
        "booked_at": "2026-04-24T08:00:00",
        "event": "India vs Australia T20",
        "venue": "Wankhede Stadium, Mumbai",
        "event_date": "2026-04-25T19:30:00",
        "seats": ["Stand D - Row 3 - Seat 7"],
        "amount": 2200,
        "payment_method": "UPI",
        "review_reason": "payment_verification_pending",
    },
    "ORD-TB-1303": {
        "domain": "ticket_booking",
        "user_email": "suresh.kumar@email.com",
        "status": "confirmed",
        "booked_at": "2026-04-21T11:00:00",
        "event": "Bangalore Literature Festival",
        "venue": "IIM Bangalore Campus",
        "event_date": "2026-05-08T09:00:00",
        "seats": ["Auditorium A - Row 6 - Seat 14"],
        "amount": 599,
        "payment_method": "Debit Card",
        "issue": "confirmation_email_not_received",
    },
    "ORD-TB-1304": {
        "domain": "ticket_booking",
        "user_email": "deepa.iyer@gmail.com",
        "status": "waitlisted",
        "booked_at": "2026-04-22T16:00:00",
        "event": "Coldplay India Tour — Mumbai",
        "venue": "DY Patil Stadium, Mumbai",
        "event_date": "2026-11-18T19:00:00",
        "seats": ["Waitlist #2847"],
        "amount": 8500,
        "payment_method": "Credit Card",
        "waitlist_position": 2847,
    },
}


# ── Lookup helpers ─────────────────────────────────────────────────────────────

def get_user(email: str) -> Union[Dict[str, Any], str]:
    """Return user dict or 'not_found'."""
    return USERS.get(email.lower().strip(), "not_found")


def get_order(order_id: str) -> Union[Dict[str, Any], str]:
    """Return order dict or 'not_found'."""
    key = order_id.strip().upper()
    return ORDERS.get(key, "not_found")
